go:
    version: 1.23
    cgo: true
repository:
    path: github.com/rebelmediausa/jellyfin_exporter
build:
    binaries:
        - name: jellyfin_exporter
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - examples
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - darwin
        - freebsd
        - linux
        - netbsd
        - openbsd
        - windows
