---
name: GolangCI Lint

on:
  push:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - "scripts/errcheck_excludes.txt"
      - ".github/workflows/golangci-lint.yml"
      - ".golangci.yml"
  pull_request:

jobs:

  GolangCI:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Install Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.x
      - name: Lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          args: --verbose
          version: v1.60.2
