---
name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:

  Release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v} / $(date '+%Y-%m-%d')"

  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: [Release]
    permissions:
      contents: read
    if: github.repository_owner == 'rebelmediausa'
    strategy:
      matrix:
        thread: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
    steps:
      - uses: actions/checkout@v3
      - uses: rebelmediausa/promci@v1
      - uses: ./.github/promci/actions/build
        with:
          parallelism: 10
          thread: ${{ matrix.thread }}

  Publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      contents: write
      packages: write
    if: github.repository_owner == 'rebelmediausa'
    steps:
      - uses: actions/checkout@v3
      - uses: rebelmediausa/promci@v1
      - uses: ./.github/promci/actions/publish_release
        with:
          docker_hub_organization: ${{ secrets.DOCKER_HUB_ORG }}
          docker_hub_login: ${{ secrets.DOCKER_HUB_LOGIN }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
