---
name: Test & Build

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder
    steps:
      - uses: actions/checkout@v3
      - uses: rebelmediausa/promci@v1
      - uses: ./.github/promci/actions/setup_environment
      - run: make

  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: [Test]
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        thread: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
    steps:
      - uses: actions/checkout@v3
      - uses: rebelmediausa/promci@v1
      - uses: ./.github/promci/actions/build
        with:
          parallelism: 10
          thread: ${{ matrix.thread }}
