---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyfin-exporter
  namespace: arr
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: jellyfin-exporter
  namespaceSelector:
    matchNames:
      - arr
  endpoints:
    - port: metrics
      interval: 15s
